---
- name: "update apt packages"
  become: yes
  apt: 
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes
  
- name: "Install Nodejs and npm"
  become: yes    
  apt:
    name: ["nodejs", "npm"]
    state: latest

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes 